#!/bin/sh
## ALIASES
#
#
#
cfg_zathura() { "$EDITOR" "$HOME"/.config/zathura/zathurarc ;}
cfg_mako() { "$EDITOR" "$HOME/.config/mako/config" ;}
cfg_vifm() { "EDITOR" "$HOME/.config/vifm/vifmrc" ;}
cfg_alacritty() { "$EDITOR" "$HOME/.config/alacritty/alacritty.yml" ;}
cfg_vim() { "$EDITOR" "$HOME/.vimrc" ;}
cfg_sway() { "$EDITOR" "$HOME/.config/sway/config" ;}
cfg_zsh() { "$EDITOR" "$HOME/.zshrc" ;}
cfg_ranger() { "$EDITOR" "$HOME/.config/ranger" ;}
cfg_waybar() { "$EDITOR" "$HOME/.config/waybar" ;}
cfg_gtk3() { "$EDITOR" "$HOME/.config/gtk-3.0/settings.ini" ;}
cfg_llpp() { "$EDITOR" "$HOME/.config/llpp.conf" ;}
cfg_dunst() { "$EDITOR" "$HOME/.config/dunst/dunstrc" ;}
cfg_sxiv() { "$EDITOR" "$HOME/.config/sxiv" ;}
cfg_yay() { "$EDITOR" "$HOME/.config/yay/config.json" ;}
cfg_youtube_viewer() { "$EDITOR" "$HOME/.config/yay/config.json" ;}
cfg_redshift() { "$EDITOR" "$HOME/.config/redshift.conf" ;}
cfg_imv() { "$EDITOR" "$HOME/.config/imv/config" ;}
cfg_gtk3() { "$EDITOR" "$HOME/.config/gtk-3.0/" ;}
cfg_mpv() { "$EDITOR" "$HOME/.config/mpv/mpv.conf" ;}
cfg_pacman() { "$EDITOR" "/etc/pacman.conf" ;}
#
rld_zsh() { .  ~/.zshrc ;}
rld_sway() { sway reload ;}
# 
alias rsync-copy="rsync -avz --progress -h"
alias rsync-move="rsync -avz --progress -h --remove-source-files"
alias rsync-update="rsync -avzu --progress -h"
alias rsync-synchronize="rsync -avzu --delete --progress -h"
#
play_wc3() { env WINEPREFIX="$HOME/.winegames/warcraft3" wine $HOME/.winegames/warcraft3/drive_c/Warcraft\ 3\ Frozen\ Throne/Frozen\ Throne.exe ;}
play_deusex() { env WINEPREFIX="$HOME/.winegames/deusex" wine $HOME/.winegames/deusex/drive_c/GOG\ Games/Deus\ Ex\ GOTY/System/DeusEx.exe ;}
play_heroes3() { env WINEPREFIX="$HOME/.winegames/heroes" wine $HOME/.winegames/heroes/drive_c/GOG Games/HoMM 3 Complete/Heroes3.exe ;}
play_df() { cd Downloads/df_linux/ || exit ; ./df ;}
play_nethack() { telnet nethack.alt.org ;}
#
alias n="nnn"
alias e='exit'
alias q='exit'
alias r='ranger'
alias c="clear"
#
aliases() { "$EDITOR" $HOME/scripts/aliases ;}
exports() { "$EDITOR" $HOME/scripts/exports ;}
scripts() { "$EDITOR" $HOME/scripts ;}
funcs() { "$EDITOR" $HOME/scripts/funcs ;}
gitdots() { git add * ; git commit -m "regular update" ; git push ;}
mpv() { DRI_PRIME=1 mpv ;}
chromium() { DRI_PRIME=1 chromium ;}
gimp() { DRI_PRIME=1 gimp ;}
executable() { chmod +x ;}
nvim_stime() { nvim --startuptime /tmp/startup.log +q ; "$EDITOR" /tmp/startup.log ;}
vim_stime() { vim --startuptime /tmp/startup.log +q ; "$EDITOR" /tmp/startup.log ;}
telegram_desktop() { DRI_PRIME=1 telegram-desktop ;}
update_grub() { sudo grub-mkconfig -o /boot/grub/grub.cfg ;}
grub_update() { sudo grub-mkconfig -o /boot/grub/grub.cfg ;}
alias sc='sc-im'
alias connection='connection.sh'
alias connect='connection.sh'
alias reconnection='connection.sh'
alias reconnect='connection.sh'
alias rg='rg -S'
alias nv='nvim'
alias cp='cp -i'
alias mv='mv -i'
alias rm='trash-put'
alias diff='vimdiff'
alias dmesg='dmesg -HL'
alias neofetch='neofetch --disable theme icons --package_managers off --uptime_shorthand on --w3m /home/gppk/pics/top.jpg --loop --crop_mode fit'
alias ka='killall'
#
alias ys='yay -S --sudoloop'
alias ysyu='yay -Syu --sudoloop'
alias ysuy='yay -Syu --sudoloop'
alias yss='yay -Ss'
alias ysi='yay -Si'
alias yq='yay -Q'
alias yqi='yay -Qi'
alias yrns='yay -Rns'
alias yrsn='yay -Rns'
#
alias ls='ls --color=auto'
alias lsla='ls -la --color=auto'
alias grep='grep -n --color=always'
#
alias todo='jrnl @todolist -n 1'
alias todolist='jrnl @todolist -n 1'
alias todoedit='jrnl @todolist -n 1 --edit'
#
vimw() { "$EDITOR" ~/vimwiki/index.wiki ;}
vw() { "$EDITOR" ~/vimwiki/index.wiki ;}
du() { du -h --max-depth=1 | sort -h -r ;}
lostfiles_relaxed() { sudo /usr/bin/lostfiles relaxed ;}
lostfiles_stricted() { sudo /usr/bin/lostfiles strict ;}
# orphans() { sudo pacman -Rns $(pacman -Qqdt) ;}
myip() { ip route ; curl ipinfo.io ;}
killX() { killall Xorg ;}
alias paclog="pacolog"
alias mutt="neomutt"
alias starwars="telnet towel.blinkenlights.nl"
alias mkdir="mkdir -pv"
alias calc='wcalc'
alias calculator='wcalc'
alias wifi-menu='sudo wifi-menu'
alias df='df -h'
alias weather-saratov="curl wttr.in/saratov"
alias weather-odintsovo="curl wttr.in/odintsovo"
alias vless='~/.vim/less.sh'
alias susp='systemctl suspend'
alias ping='ping -c 3'
alias boottime='systemd-analyze'
alias mapscii='telnet mapscii.me'
alias whoneeds='pactree -r'
alias wn='pactree -r'
alias pactree='pactree -c'
alias tree='tree -hC'
alias tree1='tree -hCL 1'
alias tree2='tree -hCL 2'
alias tree3='tree -hCL 3'
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
#
blog_new() { cd $HOME/blog/lb/ ; ./lb n ;}
blog_edit() { cd $HOME/blog/lb/ ; ./lb e ;}
blog_trash() { cd $HOME/blog/lb/ ; ./lb t ;}
blog_publish() { cd $HOME/blog/lb/ ; ./lb p ;}
blog_delete() { cd $HOME/blog/lb/ ; ./lb d ;}
blog_revise() { cd $HOME/blog/lb/ ; ./lb r ;}
